global using System;
global using System.Collections.Generic;
global using System.Data;
global using System.Data.SqlClient;
global using System.IdentityModel.Tokens.Jwt;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Security.Claims;
global using System.Text;
global using System.Text.RegularExpressions;
global using BIVN.FixedStorage.Identity.API.Authorization;
global using BIVN.FixedStorage.Identity.API.Infrastructure;
global using BIVN.FixedStorage.Identity.API.Infrastructure.Entity;
global using BIVN.FixedStorage.Identity.API.Infrastructure.Entity.Configuration;
global using BIVN.FixedStorage.Identity.API.Middlewares;
global using BIVN.FixedStorage.Identity.API.Service;
global using BIVN.FixedStorage.Identity.API.Service.Dtos;

global using BIVN.FixedStorage.Identity.Service;
global using BIVN.FixedStorage.Services.Common.API;
global using BIVN.FixedStorage.Services.Common.API.Dto;
global using BIVN.FixedStorage.Services.Common.API.Dto.Role;
global using BIVN.FixedStorage.Services.Common.API.Helpers;
global using BIVN.FixedStorage.Services.Common.API.Response;
global using BIVN.FixedStorage.Services.Common.API.User;
global using Dapper;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Filters;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.OpenApi.Models;
global using Polly;
global using Polly.Retry;
global using RestSharp;
global using Serilog;
global using Swashbuckle.AspNetCore.Annotations;
global using static BIVN.FixedStorage.Services.Common.API.Constants;
global using AllowAnonymousAttribute = BIVN.FixedStorage.Identity.API.Authorization.AllowAnonymousAttribute;
global using Authorize = BIVN.FixedStorage.Identity.API.Authorization.AuthorizeAttribute;
global using BIVN.FixedStorage.Identity.API.Attributes;
global using BIVN.FixedStorage.Services.Common.API.BackgroundJob;
global using Identity.API.Service;
