global using System;
global using System.Data.SqlClient;
global using System.Text;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.AspNetCore.Mvc.ModelBinding;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.EntityFrameworkCore.Migrations;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using Dapper;
global using Polly;
global using Polly.Retry;
global using System.ComponentModel.DataAnnotations;
global using RestSharp;
global using Newtonsoft.Json;
global using Microsoft.AspNetCore.Mvc.Filters;
global using Swashbuckle.AspNetCore.Annotations;
global using System.Text.RegularExpressions;
global using System.Security.Claims;
global using Serilog;
global using System.Collections.Concurrent;
global using System.Drawing;
global using System.Globalization;
global using CsvHelper;
global using CsvHelper.Configuration;
global using OfficeOpenXml;
global using OfficeOpenXml.Style;
global using Storage.API.Service;
global using BIVN.FixedStorage.Services.Infrastructure;
global using BIVN.FixedStorage.Services.Common.API.Response;
global using BIVN.FixedStorage.Services.Common.API;
global using BIVN.FixedStorage.Services.Storage.API.Infrastructure.Entity;
global using BIVN.FixedStorage.Storage.API.Infrastructure.Entity.Configuration;
global using BIVN.FixedStorage.Services.Storage.API.Service;
global using BIVN.FixedStorage.Services.Storage.API.Service.Dto;
global using BIVN.FixedStorage.Services.Storage.API.Middlewares;
global using BIVN.FixedStorage.Services.Common.API.Dto;
global using BIVN.FixedStorage.Services.Common.API.Helpers;

global using Authorize = BIVN.FixedStorage.Services.Storage.API.Attributes.AuthorizeAttribute;
global using BIVN.FixedStorage.Services.Storage.API.Attributes;
global using AllowAnonymousAttribute = BIVN.FixedStorage.Services.Storage.API.Attributes.AllowAnonymousAttribute;
global using BIVN.FixedStorage.Services.Common.API.Dto.Factory;
global using BIVN.FixedStorage.Services.Common.API.Enum.Storage;
global using BIVN.FixedStorage.Services.Common.API.Dto.Component;
global using BIVN.FixedStorage.Services.Storage.API.Infrastructure;
global using commonAPIConstant = BIVN.FixedStorage.Services.Common.API.Constants;
global using BIVN.FixedStorage.Services.Common.API.User;
global using Microsoft.IdentityModel.Tokens;
global using Storage.API.Service.Dto;
global using BIVN.FixedStorage.Services.Common.API.Dto.PagedList;
global using Identity.API.Service.Dtos;
global using BIVN.FixedStorage.Services.Common.API.Dto.Layout;
global using static BIVN.FixedStorage.Services.Common.API.Constants;
global using Storage.API.Middlewares;
global using Microsoft.OpenApi.Models;

global using System.Data;
