// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory.API.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20231120075932_init_tables")]
    partial class init_tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BIVN.FixedStorage.Services.Inventory.API.Infrastructure.Entity.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AuditFailPercentage")
                        .HasColumnType("float");

                    b.Property<DateTime>("InventoryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InventoryStatus")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Inventory.API.Infrastructure.Entity.AuditTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComponentCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ComponentName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Factory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("InventoryOutput")
                        .HasColumnType("float");

                    b.Property<string>("LocationName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Market")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Outbound")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Position")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double>("QuantityOfOrder")
                        .HasColumnType("float");

                    b.Property<double>("QuantityOfOutbound")
                        .HasColumnType("float");

                    b.Property<string>("SaleOrderNo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("SumOfTran")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ComponentCode");

                    b.HasIndex("InventoryId");

                    b.ToTable("AuditTargets");
                });

            modelBuilder.Entity("Inventory.API.Infrastructure.Entity.DocHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("ChangeLog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EvicenceImg")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("InventoryDocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InventoryDocId");

                    b.ToTable("DocHistories");
                });

            modelBuilder.Entity("Inventory.API.Infrastructure.Entity.DocOutput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InventoryDocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("QuantityOfBom")
                        .HasColumnType("float");

                    b.Property<double>("QuantityPerBom")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("InventoryDocId");

                    b.ToTable("DocOutputs");
                });

            modelBuilder.Entity("Inventory.API.Infrastructure.Entity.DocTypeCDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComponentCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("InventoryDocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModelCode")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double>("QuantityOfBom")
                        .HasColumnType("float");

                    b.Property<double>("QuantityPerBom")
                        .HasColumnType("float");

                    b.Property<bool>("isHighlight")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("InventoryDocId");

                    b.ToTable("DocTypeCDetails");
                });

            modelBuilder.Entity("Inventory.API.Infrastructure.Entity.HistoryOutput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DocHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("QuantityOfBom")
                        .HasColumnType("float");

                    b.Property<double>("QuantityPerBom")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DocHistoryId");

                    b.ToTable("HistoryOutputs");
                });

            modelBuilder.Entity("Inventory.API.Infrastructure.Entity.HistoryTypeCDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComponentCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("DocHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isHighlight")
                        .HasColumnType("bit");

                    b.Property<string>("ModelCode")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double>("QuantityOfBom")
                        .HasColumnType("float");

                    b.Property<double>("QuantityPerBom")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DocHistoryId");

                    b.ToTable("HistoryTypeCDetails");
                });

            modelBuilder.Entity("Inventory.API.Infrastructure.Entity.InventoryAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("InventoryAccounts");
                });

            modelBuilder.Entity("Inventory.API.Infrastructure.Entity.InventoryDoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AccountQuantity")
                        .HasColumnType("float");

                    b.Property<string>("AssemblyLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AssignedAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AuditAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AuditBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComponentCode")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ComponentName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("ConfirmAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ConfirmBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DocCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DocType")
                        .HasColumnType("int");

                    b.Property<double>("ErrorQuantity")
                        .HasColumnType("float");

                    b.Property<DateTime?>("InventoryAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("InventoryBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Layout")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LocationName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ModelCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("No")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Plant")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ProductOrderNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ReceiveAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReceiveBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SaleOrderList")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SalesOrderNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SapInventoryNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SpecialStock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("TotalQuantity")
                        .HasColumnType("float");

                    b.Property<string>("UnitPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WareHouseLocation")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("columnC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("columnN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("columnO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("columnP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("columnQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("columnR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("columnS")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ComponentCode");

                    b.HasIndex("InventoryId");

                    b.HasIndex("ModelCode");

                    b.ToTable("InventoryDocs");
                });

            modelBuilder.Entity("Inventory.API.Infrastructure.Entity.InventoryLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FactoryName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("InventoryLocations");
                });

            modelBuilder.Entity("Inventory.API.Infrastructure.Entity.AuditTarget", b =>
                {
                    b.HasOne("BIVN.FixedStorage.Services.Inventory.API.Infrastructure.Entity.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Inventory.API.Infrastructure.Entity.DocHistory", b =>
                {
                    b.HasOne("Inventory.API.Infrastructure.Entity.InventoryDoc", "InventoryDoc")
                        .WithMany("DocHistories")
                        .HasForeignKey("InventoryDocId");

                    b.Navigation("InventoryDoc");
                });

            modelBuilder.Entity("Inventory.API.Infrastructure.Entity.DocOutput", b =>
                {
                    b.HasOne("Inventory.API.Infrastructure.Entity.InventoryDoc", "InventoryDoc")
                        .WithMany()
                        .HasForeignKey("InventoryDocId");

                    b.Navigation("InventoryDoc");
                });

            modelBuilder.Entity("Inventory.API.Infrastructure.Entity.DocTypeCDetail", b =>
                {
                    b.HasOne("Inventory.API.Infrastructure.Entity.InventoryDoc", "InventoryDoc")
                        .WithMany()
                        .HasForeignKey("InventoryDocId");

                    b.Navigation("InventoryDoc");
                });

            modelBuilder.Entity("Inventory.API.Infrastructure.Entity.HistoryOutput", b =>
                {
                    b.HasOne("Inventory.API.Infrastructure.Entity.DocHistory", "DocHistory")
                        .WithMany()
                        .HasForeignKey("DocHistoryId");

                    b.Navigation("DocHistory");
                });

            modelBuilder.Entity("Inventory.API.Infrastructure.Entity.HistoryTypeCDetail", b =>
                {
                    b.HasOne("Inventory.API.Infrastructure.Entity.DocHistory", "DocHistory")
                        .WithMany()
                        .HasForeignKey("DocHistoryId");

                    b.Navigation("DocHistory");
                });

            modelBuilder.Entity("Inventory.API.Infrastructure.Entity.InventoryDoc", b =>
                {
                    b.HasOne("BIVN.FixedStorage.Services.Inventory.API.Infrastructure.Entity.Inventory", "Inventory")
                        .WithMany("InventoryDocs")
                        .HasForeignKey("InventoryId");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("BIVN.FixedStorage.Services.Inventory.API.Infrastructure.Entity.Inventory", b =>
                {
                    b.Navigation("InventoryDocs");
                });

            modelBuilder.Entity("Inventory.API.Infrastructure.Entity.InventoryDoc", b =>
                {
                    b.Navigation("DocHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
